### PR TITLE
`form_with` with `validate: false` on Rails 8 exception fix

### LINKED ISSUE #974: `form_with` default argument raises exception on Rails 8.0
### Steps to reproduce*

Use `form_with` in a view without specifying a model and without specifying `validate: true`:
```erb
<%= form_with(url: "/posts") do |form| %>
  <%# form stuff goes here %>
<% end %>
```

Here is a regression test for `test/action_view/cases/test_form_with_helpers.rb`:
```ruby
def test_form_with_without_model_without_validation
  form_with(url: '/posts') do |f|
    concat f.text_field(:cost)
  end

  expected = whole_form_with('/posts') do
    form_field('input', id: 'cost', name: 'cost', type: 'text')
  end

  assert_dom_equal expected, output_buffer
end
```

### Expected behavior*
The Rails fallback behavior should be used without any problem, like when the gem is not installed.

### Actual behavior*
Deprecation warning on Rails 7.2:
```
DEPRECATION WARNING: Passing nil to the :model argument is deprecated and will raise in Rails 8.0
```

Exception raised on Rails 8.0+:
```
ArgumentError: Passed nil to the :model argument, expect an object or false
```

### System configuration*
**Rails version**: 7.2+

**Ruby version**: 3.3

**Client Side Validations version**: 22.3.0

---

I think this problem can be solved by changing the default `model` option in `form_with` to `false` to match the expected Rails default:
https://github.com/DavyJonesLocker/client_side_validations/blob/v22.3.0/lib/client_side_validations/action_view/form_with_helper.rb#L7

I don't suspect there would be a backwards compatibility issue with this change.

The Rails change was initially made here: https://github.com/rails/rails/pull/49943
It was changed to a deprecation warning for Rails 7.2 here: https://github.com/rails/rails/pull/50931

### PR DESCRIPTION
**Pull request by maxnovee**
that should fix #974

### CODE REVIEW

**Comment by tagliala** [comment]
Ah, the logger issue.

Please allow me to fix the CI, I will then ask you to rebase

File: test/action_view/cases/test_form_with_helpers.rb [hunk 1]
```diff
@@ -67,6 +67,14 @@ def test_form_with_automatically_generate_ids
         assert_dom_equal expected, output_buffer
       end
 
+      def test_form_with_skip_validate
+        assert_nothing_raised do
+          form_with(validate: false)
+        end
+
+        assert_dom "form"
```
Comment (tagliala) [inline test/action_view/cases/test_form_with_helpers.rb:75]: in the meanwhile, this is for sure an issue to fix

**Comment by tagliala** [comment]
@maxnovee done, please rebase

**Comment by tagliala** [comment]
Great, all green. Can you:
- fix the rubocop offence. it is annotated in files tab. You should be able to run `bundle exec rubocop -a` locally and it will be fixed.
- Squash all the commit in a single one. Please adhere to the 7 rules for a good commit, as per Contributing guidelines: https://github.com/DavyJonesLocker/client_side_validations/blob/main/CONTRIBUTING.md#commits

  ```
  Fix ... (max 50 chars)

  Description of the fix (not what, why)

  Fix #974
  ```

File: test/action_view/cases/test_form_with_helpers.rb (hunk 1 above)
Comment (maxnovee) [reply test/action_view/cases/test_form_with_helpers.rb:75]: I can change to what @grantbdev added in the issue if these are a better fit
```
def test_form_with_without_model_without_validation
  form_with(url: '/posts') do |f|
    concat f.text_field(:cost)
  end

  expected = whole_form_with('/posts') do
    form_field('input', id: 'cost', name: 'cost', type: 'text')
  end

  assert_dom_equal expected, output_buffer
end
```

**Review by tagliala — APPROVED** [review]

**Comment by tagliala** [comment]
Thanks!

I'll backport this change do `22-stable` and then release 22.3.1 instead of going to 23.0 directly

**Comment by maxnovee** [comment]
My pleasure!

Looking forward to get the hotfix.

**Comment by tagliala** [comment]
22.3.1 pushed to rubygems, thanks again
